version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
   say-bye:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say PRE Bye bye"
          command: "echo Hello, World!"
       - run:
          name: "Say Bye bye"
          command: "echo Hello, World!"
       - run:
          name: "Say POST Bye bye"
          command: "echo Hello, World!"


workflows:
  say-hello-workflow: # This is the name of the workflow, feel free to change it to better match your workflow.
    jobs:
      - say-hello
      - say-bye
