version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  say-bye:
    docker:
      - image: cimg/base:current
    steps:
      - run:
          name: "Say PRE Bye bye"
          command: "echo Hello, World!"
      - run:
          name: "Say Bye bye"
          command: "echo Bye, World!"
      - run:
          name: "Say POST Bye bye"
          command: "echo Goodbye, World!"

  approval:
    type: approval

workflows:
  workflow1:
    jobs:
      - say-hello
      - say-bye

  workflow2:
    jobs:
      - say-hello
      - say-bye:
          requires:
            - say-hello
            
  workflow3:
    jobs:
      - say-hello
      - approval:
          requires:
            - say-hello
      - say-bye:
          requires:
            - approval

  nocturno:
    triggers:
      - schedule:
          cron: "30 00 * * *"
          filters:
            branches:
              only:
                - circleci-project-setup
    jobs:
      - say-hello
      - say-bye:
          requires:
            - say-hello
